version: '3.8'
services:
  garage-sale:
    image: egordoroshv/garage-sale:1.0.0
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - log:/app/server/log
      - images:/app/server/images
    env_file:
      - ./.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 60s
volumes:
  log:
  images: