version: '3.8'
services:
  garage-sale:
    image: egordoroshv/garage-sale:1.0.1
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - log:/app/server/log
      - images:/app/server/images
    env_file:
      - ./.env
    restart: unless-stopped
volumes:
  log:
  images: