version: '3.8'
services:
  garage-sale:
    image: egordoroshv/garage-sale:0.2.0
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - log:/app/server/log
      - images:/app/server/images
    env_file:
      - ./.env

volumes:
  log:
  images: