version: '3.8'
services:
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    command: mongod --quiet --logpath /dev/null 
    env_file:
      - .env
  garage-sale:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - mongodb

volumes:
  data: